language: node_js
node_js:
- lts/*
script:
- npm i bs-platform --no-save
- npm run build
after_success:
- git remote add clever git+ssh://git@push-par-clevercloud-customers.services.clever-cloud.com/app_50f92e65-3f89-4196-adb5-92ae17a8c219.git
- git push -u clever master
before_install:
    - npm i -g npm@latest
