language: node_js
node_js:
- lts/*
- '10'
deploy:
  api_key:
    secure: VZ0qIJfzy76gbzf5nPhv785tHe/ESpUJweM4cYCkDYM/HnKxTCeowUflpv5cA/DUp9hDtqurrYNiIyVOrsUeDhhLY95kdN5j5vzCiPX1kMGetTKrFB7Dq0HqB5t2mWmWUHj8W9n8fyIDY7u2PVHkIfMeizYwv+Iby3gZEqX/Cl3evO6u+k5y3tRbdBBu6gbFuS+wk9BDHQroKAh6KN94BhV30dc4Jm5ysq7pPLayWZw3kJoeODl5eKaX7sgkFlAufzB87fJkWUwwvkHiiSL+7jNPtj7NJyTGm4z298mf3KINbglgUnJ9e8s25Xh0cRwPiFGV8YU59JkuTSum28HyUIc3E3jMD3YMXd5QE9A5cUH3wEa/f/mZthrHg3S7WntdOSxkgU1uOEvTrAxKZBQWnXfawCe70BQNHtpEUaRW+X1Ii2kpmK/jsODSXTw45cFW10ZbRG0/gNPyCB81JI1uryElvkoYbhmDOy9XBjJhoRJntLoYIFYU0+oNNyz3oNDbCimXHswSvqqjh5lZ6CLf6PRe2YSiad1OT1ghrKYYGsKGpGyOYL/TpK6drdIM46KMExyKoOoMkgLAIkOPUD1qZuUjNrMIDv8zE+YZcdH/ZuoKV9H7B9TVbRVU4ehf4KcszDI4C6fOhY0yJOIC0YsdYdeaGJW6M8RTQD3axHq/KGI=
  app: noschool5
  on: develop
before_install:
    - npm i -g npm@latest
