// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("bs-axios/src/axios.js");
var Axios$1 = require("axios");

function sendMail(message) {
  var dict = { };
  dict["Content-type"] = "application/json";
  dict["Authorization"] = "API-KEY";
  var headers = Axios.$$Headers.fromDict(dict);
  Axios$1.post("https://api.sendgrid.com/v3/mail/send", message, {
            headers: headers
          }).then((function (response) {
            return Promise.resolve((console.log(response.data), /* () */0));
          })).catch((function (error) {
          return Promise.resolve((console.log(error), /* () */0));
        }));
  return /* () */0;
}

exports.sendMail = sendMail;
/* axios Not a pure module */
