// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function sendMail(message) {
  var defaultHeaders = ({
          "Content-Type": "application/json",
          "Authorization": "la superbe cle"
        });
  var payload = { };
  payload["personalizations"] = message;
  fetch("https://api.sendgrid.com/v3/mail/send", Fetch.RequestInit.make(/* Post */2, Caml_option.some(defaultHeaders), Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
          return prim.json();
        }));
  return /* () */0;
}

exports.sendMail = sendMail;
/* No side effect */
