// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fetch = require("bs-fetch/src/Fetch.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function sendMail(message) {
  var defaultHeaders = ({
          "Content-Type": "application/json",
          "Authorization": "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"
        });
  var payload = { };
  payload["personalizations"] = message;
  return fetch("https://api.sendgrid.com/v3/mail/send", Fetch.RequestInit.make(/* Post */2, Caml_option.some(defaultHeaders), Caml_option.some(JSON.stringify(payload)), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* () */0)).then((function (prim) {
                return prim.json();
              }));
}

exports.sendMail = sendMail;
/* No side effect */
