// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var AmqpConnectionManager = require("bs-amqp-connection-manager/src/AmqpConnectionManager.bs.js");
var AmqpConnectionManager$1 = require("amqp-connection-manager");

var connection = AmqpConnectionManager$1.connect(["amqp://qzscetiz:iLJmX80CVSklfcVeS1NH81AwaHLSikPh@crow.rmq.cloudamqp.com/qzscetiz"], undefined);

Curry._2(AmqpConnectionManager.AmqpConnectionManager.on, connection, /* `disconnect */[
      -381393828,
      (function (err) {
          console.error(err);
          return /* () */0;
        })
    ]);

Curry._2(AmqpConnectionManager.AmqpConnectionManager.on, connection, /* `connect */[
      360725482,
      (function (param) {
          console.info("connected!");
          return /* () */0;
        })
    ]);

var Amqp = /* alias */0;

var queue_name = "QviewCourse";

exports.Amqp = Amqp;
exports.queue_name = queue_name;
exports.connection = connection;
/* connection Not a pure module */
