// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var BsCron = require("bs-cron/src/BsCron.bs.js");

var job = BsCron.CronJob.make(/* `CronString */[
      870007071,
      "* * * * * *"
    ], (function (param) {
        console.log("Just doing my job");
        return /* () */0;
      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);

var minuteJob = BsCron.CronJob.make(/* `CronString */[
      870007071,
      "30 * * * * *"
    ], (function (param) {
        console.log("Just doing my minute job");
        return /* () */0;
      }), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0);

job.start();

minuteJob.start();

exports.job = job;
exports.minuteJob = minuteJob;
/* job Not a pure module */
