// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

Pervasives.print_string("Hello world equipe 5!");

Pervasives.print_newline(/* () */0);

/*  Not a pure module */
