// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Express = require("express");

var app = Express();

app.get("/", (function (param, res) {
        res.send("QSI NoSchool 2k20 DSI");
        return /* () */0;
      }));

app.listen(8080);

exports.app = app;
/* app Not a pure module */
