// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");
var ReceiverNewUser$ReasonmlDemoModules = require("./ReceiverNewUser.bs.js");
var ReceiverElevPriv$ReasonmlDemoModules = require("./ReceiverElevPriv.bs.js");
var ReceiverViewCourse$ReasonmlDemoModules = require("./ReceiverViewCourse.bs.js");

Pervasives.print_string("Startinq Noschool amqp message listener");

Pervasives.print_newline(/* () */0);

var receiverElevPriv = ReceiverElevPriv$ReasonmlDemoModules.connection;

var receiverNewUser = ReceiverNewUser$ReasonmlDemoModules.connection;

var receiverViewCourse = ReceiverViewCourse$ReasonmlDemoModules.connection;

exports.receiverElevPriv = receiverElevPriv;
exports.receiverNewUser = receiverNewUser;
exports.receiverViewCourse = receiverViewCourse;
/*  Not a pure module */
