// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Process = require("process");
var Papaparse = require("papaparse");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var args = Process.argv;

var csvFile = args[args.length - 2 | 0];

var allLines = Fs.readFileSync(csvFile, "utf8");

var $$Error = { };

var Meta = { };

var Results = { };

var parseData = Papaparse.parse(allLines).data;

var headers = Belt_Array.slice(parseData, 0, 1)[0];

exports.args = args;
exports.csvFile = csvFile;
exports.allLines = allLines;
exports.$$Error = $$Error;
exports.Meta = Meta;
exports.Results = Results;
exports.parseData = parseData;
exports.headers = headers;
/* args Not a pure module */
