// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Axios = require("bs-axios/src/axios.js");
var Axios$1 = require("axios");
var AmqpConnectionManager = require("bs-amqp-connection-manager/src/AmqpConnectionManager.bs.js");

function sendMail(msg, channel) {
  var message = JSON.parse(msg.content.toString());
  var dict = { };
  dict["Content-type"] = "application/json";
  dict["Authorization"] = "Bearer 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";
  var headers = Axios.$$Headers.fromDict(dict);
  return Axios$1.post("https://api.sendgrid.com/v3/mail/send", message, {
                  headers: headers
                }).then((function (response) {
                  AmqpConnectionManager.Channel.ack(channel, msg);
                  console.info(response);
                  console.info("Email envoy\xc3\xa9");
                  return Promise.resolve(response.data);
                })).catch((function (error) {
                AmqpConnectionManager.Channel.nack(channel, msg);
                console.info(error);
                return Promise.resolve(error);
              }));
}

var Amqp = /* alias */0;

exports.Amqp = Amqp;
exports.sendMail = sendMail;
/* axios Not a pure module */
